### ISSUE TITLE
Rarbg add-on 

### ISSUE THREAD

**Issue by KillerCroc1** [sebastiencs/rarbg-addon#1]
Hello your add-on is down on stremio any update when it will return ?

**Comment by sebastiencs** [comment]
It seems that there was a problem with rarbg domain:  
https://github.com/rarbg/torrentapi/issues/3#issuecomment-285945685

It should works now

**Comment by KillerCroc1** [comment]
Awesome man thanks love the add-on along with everyone on the community page ;-) any chance of a wwe add-on ??

**Comment by KillerCroc1** [comment]
Your add-on is down again :-(

**Comment by sebastiencs** [comment]
It's not my addon. It's rarbg's website/api: https://torrentapi.org/

**Comment by KillerCroc1** [comment]
Ahhh man that sucks :-( just a question can you do anything with these
sites for stremio ? https://www.mobdro.com/ https://terrariumtv.com as
would be good if you could do something with them also ;-) a fall back for
rarbg is needed for issues like this ;-)

**Comment by KillerCroc1** [comment]
ok i understand that the rarbg api is down and seems out :-( is this why
you have removed your add-on ?? whats next for your add-on as it had a lot
of potential
