### ISSUE TITLE
Not showing any content

### ISSUE THREAD

**Issue by imurreflection** [sebastiencs/rarbg-addon#14]
I m not getting any content from rarbg add-on in Stremio. I uninstalled and installed the add-on several times. Please advise

**Comment by woutcam** [comment]
I can confirm. Could you please take a look at your addon. Apparently something is down or malfunctioning.

**Comment by sebastiencs** [comment]
@imurreflection @woutcam Do you still have the issue ?

**Comment by KillerCroc1** [comment]
Yes the add-on is completely down and has been for some time :-( please fix

**Comment by imurreflection** [comment]
Unfortunately, yes, I still don't see any results from rarbg. Surprisingly, in another add-on ..Morpheus, I can see the results from rarbg but only till 1080p not 4K

**Comment by imurreflection** [comment]
I apologize, please ignore, I just checked again and found that results are available now from rarbg uptill 4k. Thank you. Could you please provide us some input as to why this failed and if there is anything as a user we can do to avoid it breaking again and wait for a long time to get a fix. Many thanks in advance

**Comment by KillerCroc1** [comment]
@imurreflection what are you using to get his add-on to work ??

**Comment by imurreflection** [comment]
I am using Stremio Beta 0.45.0 android version and it has always worked
..it was not showing content from rarbg but always shows content from YTS,
The Pirate Bay and Iberium

**Comment by KillerCroc1** [comment]
Strange I'm using 0.91.0 android beta it was showing now it not same with windows and Android TV :-(

**Comment by imurreflection** [comment]
Please install Stremio for android TV beta version from Aptoide TV Apk and
it will work

**Comment by KillerCroc1** [comment]
I did that it's not working at all

**Comment by imurreflection** [comment]
Strange, I installed 0.91 Beta from Play Store and even that is working fine but it does not show content from rarbg. I played one 1080p movie and it worked fine.

**Comment by KillerCroc1** [comment]
I think it could be a stremio issue not the add-on

**Comment by KillerCroc1** [comment]
@sebastiencs the stremio team are saying you need to fix your add-on as you have two endpoints set up you have your add-on endpoint chapu.is and best4stremio.space that is Juan Carlos 2 or popcontime add-on endpoint that is messing everything up man I have this info direct from a stremio Dev that looked into the issue
