### ISSUE TITLE
add-on  rarbg 

### ISSUE THREAD

**Issue by KillerCroc1** [sebastiencs/rarbg-addon#3]
hopefully not annoying you here but getting reports that your add-on is down :-( and i can confirm its not available on the addons.strem.io page hopefully nothing serious is wrong with the add-on

**Comment by sebastiencs** [comment]
There are some problems with the server. It will be up soon.

**Comment by KillerCroc1** [comment]
Awesome man ;-) keep up the fantastic work ;-) stremio is now on iOS is
there a way for the rarbg add-on to be available on stremio iOS ??

**Comment by KillerCroc1** [comment]
any update ? are we speaking about Monday or something before its back as seems like quite a big issue :-(
