### ISSUE TITLE
Rarbg

### ISSUE THREAD

**Issue by KillerCroc1** [sebastiencs/rarbg-addon#5]
Hey wwe is available on rarbg but not your add-on can you please add updated wwe content ??

**Comment by sebastiencs** [comment]
What is wwe ?

**Comment by KillerCroc1** [comment]
World wrestling entertainment i has shows like raw smack down and special
events like this Sunday we have wrestlemania ;-)

**Comment by KillerCroc1** [comment]
if you can find a way to do a live stream of wrestlemania on stremio you would be a lifesaver for many of your fans :-)
