### ISSUE TITLE
Strange issue 

### ISSUE THREAD

**Issue by KillerCroc1** [sebastiencs/rarbg-addon#9]
When trying to install your add-on I get a black page with a cactus with word blog along with find me on github and twitter underneath that it says writing 2017-04-11 setting up emacs for react js 
And 2017-04-11 Hello world

**Comment by sebastiencs** [comment]
You try to install it from http://addons.strem.io?

**Comment by KillerCroc1** [comment]
Yes it was not showing on their either

**Comment by KillerCroc1** [comment]
issue has been resolved :-) can you make an addon for Zooqle they use imdb this add-on along with your rarbg add-on would make you and stremio unstoppable  https://zooqle.com/help/api.html
